# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
since: 2015
title: ADoyle 的博客
subtitle:
description: 大自然的搬运工
author: ADoyle
language: zh-CN
timezone: Asia/Shanghai
avatar: https://avatars2.githubusercontent.com/u/1998490?v=3&s=460

links_title: 友情连接
links:

social:
    GitHub: https://github.com/adoyle-h
    豆瓣: http://www.douban.com/people/adoyle/
    Email: adoyle.h@gmail.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://adoyle.me/blog
root: /blog/
permalink: :title.html
permalink_defaults:
    category: unclassified

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: codes
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
auto_spacing: false
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: true

# Category & Tag
default_category: unclassified
category_map:
  技术: tech
  运维: ops
  生活: life
  设计: design
  工作: work
  产品: product
  管理: cooperation
  翻译: translation
  前端: fe
  后端: server
  经验: exp
  杂谈: ramb
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm Z

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: fluid # https://github.com/fluid-dev/hexo-theme-fluid

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:adoyle-h/blog.git
  branch: gh-pages
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

toc:
  maxDepth: 3
  bullets: "-"
  firsth1: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  content_limit: 300
  content_limit_delim: ' '
  order_by: -date

markdown:
  preset: 'default'

  render:
    html: true  # it must be true
    xhtmlOut: true
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: false
    quotes: '“”‘’'

  enable_rules:
  disable_rules:

  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-container

  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'

  images:
    lazyload: false
    prepend_root: false
    post_asset: false

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true

category_generator:
  per_page: 10
  order_by: -date

index_generator:
  path: ''
  per_page: 10
  order_by: -date
  pagination_dir: page

archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

tag_generator:
  per_page: 20
  order_by: -date
  enable_index_page: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .
  # plugins: 'nib'

html_minifier:
  exclude:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  # Ignore '<!-- more -->' https://hexo.io/docs/tag-plugins#Post-Excerpt
  # ignoreCustomComments: []
  removeComments: true
  removeEmptyAttributes: false
  removeScriptTypeAttributes: false
  removeStyleLinkTypeAttributes: false
  minifyJS: true
  minifyCSS: true
